Home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "Home"

urlpatterns = [

    path('', views.index.as_view(), name = "home"),
    path('home/', views.index.as_view(), name = "home"),
    path('transcribe/', views.TranscribingAccounts.as_view(), name = "transcribe"),
    path('bid/', views.BiddingAccounts.as_view(), name = "bid"),
    path('take/', views.TakeAccounts.as_view(), name = "take"),
    path('payment/', views.view_paypal, name ='payment'),
    path('payment-done/', views.payment_done, name= 'payment-done'),
    path('payment-cancelled/', views.payment_canceled, name = 'payment-cancelled'),
    path('product/<slug>/', views.Product.as_view(), name = "product" ),
    path('checkout/', views.Checkout.as_view(), name = 'checkout'),
    path('order-summary/', views.OrderSummaryView.as_view(), name = 'order-summary'),
    path('add_to_cart/<slug>/', views.add_to_cart, name = 'add_to_cart'),
    path('remove_from_cart/<slug>/', views.remove_from_cart, name = 'remove_from_cart'),
    path('remove_item_from_cart/<slug>/', views.remove_single_item_from_cart, name = 'remove_item_from_cart'),
    path('sell-account/', views.Sell_item.as_view(), name= "sell_account"),
    path('edit-account/<slug>/', views.Sell_item_Update.as_view(), name= "edit_account"),
    path('sale_account/', views.SaleAccountView.as_view(), name='sale_account'),
   
]

dashboard/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "dashboard"

urlpatterns = [
  path('withdraw/', views.WithdrawalView.as_view(), name = "withdraw"),
  path('validate_withdraw/', views.validate_widthrawal, name = "Validate_withdraw"),
  path('transactions/', views.TransactionsView.as_view(), name = "transactions"),
  path('release_payment/', views.Release_Payment.as_view(), name='Release_Payment'),
  path("validate_release/", views.validate_release, name = "validate_release"),
  path("refund/", views.RefundView.as_view(), name = "refund"),
  path("valid_refund/", views.validate_refund, name = "valid_refund"),
  path("notifications", views.order_notification, name ="order_notification"),
  path("email/", views.email_template, name ="email")

]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('', include('Home.urls' , namespace = "Home")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('dashboard/', include('dashboard.urls')),
    path("mobile/", include("MpesaApp.urls")),
    path("unlocks/", include("UnlocksApp.urls")),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/models.py
from datetime import datetime
from django.db import models
from django.shortcuts import reverse
from django.conf import settings
from django_countries.fields import CountryField


from django.template.defaultfilters import slugify
from paypal.standard.ipn.signals import valid_ipn_received
from autoslug import AutoSlugField
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField
import time


class Products(models.Model):
    title = models.TextField()
    description = models.TextField()
    price = models.TextField()
    

    def __str__(self):
        return self.title

Category_choices={

("s","Bidding Account"),
("sw", "Take Account"),
("OW", "Transcribing Account")

}

Label_choices={

("P","primary"),
("S", 'secondary'),
("D", "danger")

}

Level_choices = {

    ("Ivy","Ivy"),
    ("Juniour","Junior"),
    ("Intermediate","Intermediate"),
    ("Senior","Senior"),
    
}

class Item(models.Model):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE,blank = True, null = True, editable = False)
    created_at = models.DateTimeField(auto_now_add= True, blank = True, null = True )
    title = models.CharField(max_length = 100)
    slug = models.SlugField(blank = True, null = True)
    price = models.FloatField(default = 0.0)
    discountprice = models.FloatField(blank= True, null = True)
    category = models.CharField(choices = Category_choices, max_length=2)
    label = models.CharField(choices = Label_choices, max_length=1)
    Level = models.CharField(choices = Level_choices, max_length = 15 ,blank= True, null = True)
    finished_orders = models.IntegerField(default = 1)
    rating = models.IntegerField(default = 50 )
    Reviews =models.IntegerField( default = 1)
    profile = models.CharField( max_length = 20)
    description = models.TextField()
    diplay_pic = models.ImageField(upload_to = "display_pics/%Y%m%d/", max_length =255 )
    contact = models.CharField(max_length=15 ,null = True,blank= True)
    sold = models.BooleanField(default=False)
    # purchased = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("Home:product", kwargs ={
             'slug': self.slug
        })
    
    def get_add_to_cart_url(self):

        return reverse("Home:add_to_cart", kwargs ={
             'slug': self.slug
        })

    def get_discount_price(self):
        discount = self.price - self.discountprice
        return discount

    def get_remove_from_cart_url(self):
        return reverse("Home:remove_from_cart", kwargs ={
             'slug': self.slug
        })
    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title)
    #     super(Item, self).save(*args, **kwargs)

    def get_days(self):
        d1 = timezone.now()
        d2 = self.created_at
        
        dya =  abs(d1-d2).days
        mytuple = (str(dya), "days")
        days = " ".join(mytuple)
        if dya > 0:
            return days
        else:
            seconds = abs(d1-d2).seconds
            houred = round(seconds / 3600)
            
            mytuple = (str(houred), "hours")
            hours = " ".join(mytuple)
            return hours


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE)
    item = models.ForeignKey(Item, on_delete = models.CASCADE)
    quantity = models.IntegerField(default= 1)
    ordered = models.BooleanField(default = False)

    def __str__(self):
        return f"{self.quantity} of {self.item}"
    def after_discount_price(self):
        discounted_price = self.item.price - self.item.discountprice
        return discounted_price

    def get_total_item_price(self):
        price = int(self.quantity) * float(self.item.price)
        print(self.item.price, self.quantity, price, "this nown")
        return price

    def get_total_discount_item_price(self):
        discounted_price = self.item.price - self.item.discountprice

        return self.quantity * discounted_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()



    def get_final_price(self):

        if self.item.discountprice > 0:

            results= self.get_total_discount_item_price()
            return results
            print(results, "get final price for discount")

        else:
            results = self.get_total_item_price()
            print(results, "get final price no discount")

            return results


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateField(auto_now_add = True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default = False)
    seller = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE, related_name="user", blank=True, null = True)
    amount = models.IntegerField(default=0.0)
    released = models.BooleanField(default=False)
    refund = models.BooleanField(default=False)
    billing_address = models.ForeignKey(
        "BillingAddress", on_delete = models.SET_NULL, blank = True, null = True)


    def __str__(self):
        return "{}:{}".format(self.id, self.user.username)

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()

            print(total)
            # total += float(od1)
        return total

class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE)
    street_address = models.CharField(max_length = 100)
    apartment_address = models.CharField(max_length = 100)
    country = CountryField(multiple = False)
    zip_code = models.CharField(max_length = 100, blank= True, null=True)
    phone_number = PhoneNumberField(max_length=20, blank= True, null=True)
    
    def __str__(self):
        return self.user.username

Home/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from django.forms import ModelForm
from .models import Item
from phonenumber_field.formfields import PhoneNumberField


from bootstrap_modal_forms.forms import BSModalForm

class SaleAccountForm(BSModalForm):
    class Meta:
        model = Item
        fields = "__all__"


PAYMENT_CHOICES = (
('P','Paypal'),
('M','Mpesa')
)
class CheckoutForm(forms.Form):
    street_address = forms.CharField( widget = forms.TextInput(attrs = {
    'placeholder':"Address 1 for street ","class": "form-control"
    }) )
    apartment_address = forms.CharField(required = False, widget = forms.TextInput(attrs = {
    'placeholder':"Address 2 for Apartment or suite","class": "form-control"
    }))
    country = CountryField(blank_label='(select country)').formfield(widget = CountrySelectWidget(attrs = {
    'class': "custom-select d-block w-100"
    }))
    phone_number = PhoneNumberField(widget=forms.TextInput(attrs={'placeholder':('Enter phone number starting with countrycode i,e +2547xxxx '),"class": "form-control" }), 
            label=("Phone number"), required=True)

    zip_code = forms.CharField(widget = forms.TextInput(attrs = {
        "class": "form-control"
    }))
    same_billing_address = forms.BooleanField(required = False)

    save_info =  forms.BooleanField(required = False)

    payment_option =  forms.ChoiceField( widget = forms.RadioSelect, choices=PAYMENT_CHOICES )
    

class Mpesa_checkout(forms.Form):
    
     phone_number = forms.CharField( widget = forms.TextInput(attrs = {
    'placeholder':"2547xxxxxxxxx  "}))
    
class Mpesa_c2b_checkout(forms.Form):

    mpesa_code = forms.CharField( widget = forms.TextInput(attrs = {
    'placeholder':" i.e MNxxxxx "}))

class Sell_item(ModelForm):
    
    class Meta:
        model = Item
        fields = '__all__'
        

Home/templates/exam1.html
<html>
        {% extends "base.html"%}
        {%  load crispy_forms_tags %}
        {% load  staticfiles %}
  <head>
    <script type="text/javascript">

      function handleIt() {
        alert("hello");
      }

    </script>
  </head>

<body>
    {% block content %}
    <form name="myform" action="javascript:handleIt()">
      <input name="Submit"  type="submit" value="Update"/>
    </form>
    {% endblock %}
</body>
</html>

Home/templates/example.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% extends "base.html"%}
{% load  staticfiles %}

  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
   

   
    </head>
  
  <body>
      {% block content %}
    
      <div class = "container my-5 pt-5">
            <form name="myform" id ="myform" >
                <label> hey see this</label>
                <input name="pure"  type="text" value="add some"/>
                  <input name="Submit"  type="submit" value="Update"/>
                </form>
      </div>
      
     
        
       
        {% endblock%}

        <script type="text/javascript">
            $("#myform").submit(function(event) {
            event.preventDefault();
            alert("hello");
            // run a function here
            // function handleIt() {
                        
            //             }

});
           
      
          </script>
  </body>
</html>

Home/templates/index.html
<!DOCTYPE html>
{% extends "base.html"%}
<html lang="en
" dir="ltr">

  <head>
    <meta charset="utf-8">
    <title></title>

  </head>
  {% load  staticfiles %}

  <link rel = 'stylesheet' href = "{% static "css/bootstrap.min.css" %}" type ='text/CSS' >

  <body>

    {% block content %}


          <div class = 'container'  >
              <p>hi! its good to have no bugs</p>
              {% for i in object_list %}
              <li>{{ i }}</li>
              {% endfor %}
          </div>

    {% endblock%}

    

  </body>
</html>

Home/templates/nav.html
{% load cart_template_tags %}
{% load static %}

    <nav class="navbar fixed-top navbar-expand-lg  navbar-dark indigo mb-5 scrolling-navbar">
        <div class = 'container' >
            <a class="navbar-brand" href="/home/">
              <img src="{% static 'whitelogo.png' %}" height="45px" alt="">
              <!-- <h1>
                <span class="badge badge-pill danger-color">
                  <i style="font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif ;">Freelancing Accounts</i>
                </span>
              </h1> -->
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="/home/"> Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class = "nav-link" href="/sell-account/" >
                    Sell Account
                  </a>
                </li>
                

                <li class="nav-item">
                  <a class = "nav-link" href="/unlocks/" >
                    Unlocks & Logins
                  </a>
                </li>
                <li class="nav-item">
                  <a class = "nav-link" href="/" >
                    Contacts
                  </a>
                </li>

              

                
              </ul>

        
        
        
            </div>

            
            <ul class="navbar-nav nav-flex-icons mx-right">

              {%  if request.user.is_authenticated  %}

              
             
     
             
                <li class="nav-item">
                  <a class="nav-link waves-effect " href = "{% url "Home:order-summary" %}">
                    <span class="badge red z-depth-1 badge-pill mr-1"> {{ request.user|cart_item_count }}</span>
                    <i class="fas fa-shopping-cart"></i>
                    <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                  </a>
                  <!-- <li class="nav-item">
                    <a class="nav-link" href=" /accounts/logout/"> Logout </a>
                  </li> -->

                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle border border-light rounded waves-effect  waves-light" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-user-check"></i>  {{request.user}}
                    </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                        <a class="dropdown-item" href="">Account balance : <strong>{{ request.user|account_cash }} USD</strong></a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/dashboard/release_payment/">Release payment</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/dashboard/transactions/">Orders and Transactions
                          <Sup>
                            <span class="badge warning-color badge-pill z-depth-1 mr-1 animated heartBeat infinite" id="notification1"></span>
                          </Sup>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/dashboard/withdraw/">Withdraw
                          
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/dashboard/refund/">Refund money </a>
                        <div class="dropdown-divider"></div>
                      
                        <a class="dropdown-item border border-light rounded waves-effect  waves-light" data-toggle="modal" data-target="#logout">
                          <i class="fas fa-sign-out-alt"></i>
                          Logout
                        </a>

                      </div>


                  </li>
                {% else %}
                  <li class="nav-item active" > <a class="nav-link" href="#">|</a> </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/accounts/signup/"> Register </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link " data-toggle="modal" data-target="#sign_in"> 
                      <i class="fas fa-sign-in-alt"></i> Login </a>
                  </li>
                  {% endif %}
      
                </ul>
          </div>
        </nav>
        <!-- <script>
  
          (function poll(){
            console.log("hey")
            $.ajax({
               url: "{% url  'dashboard:order_notification' %}",
               type:"GET", 
               success: function(data){
                  console.log(data)
        
                  document.getElementById("#notification1").innerHTML = "Your Item was ordered"
                  
        
            }, dataType: "json", complete: poll, timeout: 300000 });
            })();
        </script> -->

Home/templates/product-page.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html"%}
{% load staticfiles %} 
<head>
  {% block meta_tags %}
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Freelancing Accounts</title>
  <meta name="description" content="Online Market place for freelancing accounts. Buy varified freelanicing accounts">
  <meta name="keywords" content="freelancingAccounts, accounts,Accountsplace, unlocks, buy freelancing accounts ">

  {% endblock %}
</head>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%} " rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css'%}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %} " rel="stylesheet">

<body>
    
 {% block content %}



  <!--Main layout-->
  <main class="">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
         
          <!-- card for iamge  -->
          <div class="card card-cascade wider">
              
              <!--Card image-->
              <div class="view view-cascade overlay">
                  <img  class="card-img-top" src="{{ object.diplay_pic.url }}" alt="picture not available" style="height: 300px;" >
                  
                  <a href="#!">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">

                  
                  <h5 class="card-header-subtitle mb-0"> {{ item.get_category_display }}</h5>
                  <span class="badge badge-pill  {{ item.get_label_display }}-color">{{item.Level}}</span>
                  
                </a>
                
                <!-- row  for orders and reviews -->
                <h4 class="font-weight-bold yellow-text mt-2 mb-2">
                   Profile :{{object.profile}}
                  </h4> 
                <div class = "row  wOW fadeIn">
                  <div class = " col-4 text-center  ">
                    <h5 class = "green-text"> {{item.finished_orders}}</h5>
                    <p> finished orders<p>
                  </div>
                  
                  
                      <div class = "col-4 text-center  ">
                        <h5 class = "green-text"> {{ item.rating}}%</h5>
                        <p> Ratings  <p>
                      </div>

                      <div class = " col-4 text-center ">
                      <h5 class = "green-text"> {{item.Reviews }}</h5>
                        <h6>  Reviews </h6>
                      </div>
                </div>

                <hr class = mb-5>
                {% if request.user == object.created_by %}

                <h5><i class="fas fa-link"></i> Reffer people to your product via this Link </h5> 
               
                   <input type="text" value="{{ request.build_absolute_uri }}" id="teks">
                    

                    <button class = "btn btn-primary" onclick="myFunction()"> Copy </button>

                {% else %}
                
                <h5 class = "grey-text pb-2"> <i class="fas fa-upload"></i> Posted {{object.get_days}} ago.</h5>

               
               {% endif %}
                
                    
                  
                </strong>

              </h5>
               
              </div>
              <!--Card content-->

            </div>
           <!-- card for image  -->

          

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge {{ object.get_label_display }}-color mr-1">{{ object.get_category_display }}</span>
              </a>
              <h3> <strong> {{object.title}} </strong></h3>
            </div>

            <p class="lead">

              {% if object.discountprice %}
              <span class="mr-1">
                <del>$ {{ object.price }}/=</del>
              </span>
              <span>$ {{ object.get_discount_price }} /=</span>
              {% else %}
              <span>$ {{ object.price }} /=</span>

              {% endif %}
            </p>
            {% if object.sold %}
            <span class="badge info-color mr-1">Already Sold</span>

            {% else %}
            <span class="badge success-color mr-1">In stock</span>

            {% endif %}

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            

            <a  href = " {{ object.get_add_to_cart_url }}" class="btn btn-primary  " >Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            
              <a  href = " {{  object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p" >Remove From cart
            
                </a>
            
            {% if request.user == object.created_by %}

            <a  href = " {% url 'Home:edit_account' slug=object.slug %}" class="btn btn-danger btn-md my-0 p" >Edit
            
              </a>

              
            {% endif %}

              <hr class="mt-3">
              <i class="fas fa-phone-square-alt"></i> <h2 class=""> contacts</h2>
              {% if  request.user.is_authenticated %}
              <h5 class=" mr-auto ml-auto dark-grey-text">
                contact the owner: {{ object.contact }}
              </h5>

              {% else %}
              <a href="/accounts/signup/"> <button class="btn btn-warning"> <i class="fas fa-phone-alt"></i> Call Seller </button></a>
              {% endif %} 

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Related Accounts to Check </h4>

          <p>Like what you see? If not, don't give up. We still have more in store perfectly tailored for you.
            click any of the below products to be directed back to more accounts to select from.
          </p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

      {% if r_items.exist %}
        {% for rtem in r_item %}
        <div class=" col-lg-4 mb-4">

          <!--Card-->
          <div class="card card-cascade ">
            
            <!--Card image-->
            <div class="view  text-white view-cascade gradient-card-header blue-gradient">

                <!-- Title -->
                <a href="{{ rtem.get_absolute_url }}"  class = "pink-hover lighten-2-hover">
                  <h2 class="card-header-title text-white mb-3 mt-2"><strong>{{ rtem.title }}</strong></h2>
                </a>
                <!-- rating -->

                    <span id="rateMe2"  class="empty-stars"></span>
                  
                  
                  <!-- rating.js file -->
                  <script src="{% static 'js/addons/rating.min.js'%}"></script>
            
              </div>
            

            <!--Card content-->
            <div class="card-body text-center">
              <!--Category & Title-->
              <a href="" class="grey-text">

                
                <h5 class="card-header-subtitle mb-0"> {{ rtem.get_category_display }}</h5>
                <span class="badge badge-pill  {{ rtem.get_label_display }}-color">{{rtem.Level}}</span>
                
              </a>
              <p> Rating :{{ rtem.rating}}% </p>
              <!-- row  for orders and reviews -->
              <h4 class="font-weight-bold blue-text">
                  <strong>  Ksh:
                    {% if rtem.discountprice %}
                      {{ rtem.get_discount_price }}
                    {% else %}
                      {{ rtem.price}}
                    {% endif %}

                /= </strong>
                </h4> 
              <div class = "row  wOW fadeIn">
                <div class = "col-6 col-lg-6 col-md-6 text-center mr-auto ml-auto ">
                  <h5 class = "green-text"> {{rtem.finished_orders}}</h5>
                  <p> finished orders<p>
                </div>
                
                    <div class = "col-6 col-md-6 text-center ">
                    <h5 class = "green-text"> {{rtem.Reviews }}</h5>
                      <h6> Reviews</h6>
                    </div>
              </div>

              <a href="{{ rtem.get_absolute_url }}" class="btn btn-primary"> Buy Account </a>
              
                  
                
              </strong>

            </h5>
              <div>
              
            </div>

            </div>
            <!--Card content-->

          </div>
          <!--Card-->

        </div>
        {% endfor %}
      {% else %}
        {% for nrtem in nr_item %}
        <div class=" col-lg-4 mb-4">

          <!--Card-->
          <div class="card card-cascade ">
            
            <!--Card image-->
            <div class="view  text-white view-cascade gradient-card-header blue-gradient">

                <!-- Title -->
                <a href="{{ nrtem.get_absolute_url }}"  class = "pink-hover lighten-2-hover">
                  <h2 class="card-header-title text-white mb-3 mt-2"><strong>{{ nrtem.title }}</strong></h2>
                </a>
                <!-- rating -->

                    <span id="rateMe2"  class="empty-stars"></span>
                  
                  
                  <!-- rating.js file -->
                  <script src="{% static 'js/addons/rating.min.js'%}"></script>
            
              </div>
            

            <!--Card content-->
            <div class="card-body text-center">
              <!--Category & Title-->
              <a href="" class="grey-text">

                
                <h5 class="card-header-subtitle mb-0"> {{ nrtem.get_category_display }}</h5>
                <span class="badge badge-pill  {{ nrtem.get_label_display }}-color">{{ nrtem.Level}}</span>
                
              </a>
              <p> Rating :{{ nrtem.rating}}% </p>
              <!-- row  for orders and reviews -->
              <h4 class="font-weight-bold blue-text">
                  <strong>  Ksh:
                    {% if nrtem.discountprice %}
                      {{ nrtem.get_discount_price }}
                    {% else %}
                      {{ nrtem.price}}
                    {% endif %}

                /= </strong>
                </h4> 
              <div class = "row  wOW fadeIn">
                <div class = "col-6 col-lg-6 col-md-6 text-center mr-auto ml-auto ">
                  <h5 class = "green-text"> {{ nrtem.finished_orders}}</h5>
                  <p> finished orders<p>
                </div>
                
                    <div class = "col-6 col-md-6 text-center ">
                    <h5 class = "green-text"> {{ nrtem.Reviews }}</h5>
                      <h6> Reviews</h6>
                    </div>
              </div>

              <a href="{{ nrtem.get_absolute_url }}" class="btn btn-primary"> Buy Account </a>
              
                  
                
              </strong>

            </h5>
              <div>
              
            </div>

            </div>
            <!--Card content-->

          </div>
          <!--Card-->

        </div> 
        {% endfor %}

      {% endif %}
        
      </div>
      <!--Grid row-->

      
    </div>
  </main>
  <!--Main layout-->

  <!--Footer-->
  
  <!--/.Footer-->


  <!-- SCRIPTS -->
  <!-- JQuery -->
  {% endblock %}

  {% block scripts %}
  <script>
      function myFunction() {
        var copyText = document.getElementById("teks");
        copyText.select();
        copyText.setSelectionRange(0, 99999)
        document.execCommand("copy");
        alert("Copied the link: " + copyText.value);
      }
 </script>

 

  
  {% endblock %}
</body>

</html>