Home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "Home"

urlpatterns = [

    path('', views.index.as_view(), name = "home"),
    path('home/', views.index.as_view(), name = "home"),
    path('transcribe/', views.TranscribingAccounts.as_view(), name = "transcribe"),
    path('bid/', views.BiddingAccounts.as_view(), name = "bid"),
    path('take/', views.TakeAccounts.as_view(), name = "take"),
    path('payment/', views.view_paypal, name ='payment'),
    path('payment-done/', views.payment_done, name= 'payment-done'),
    path('payment-cancelled/', views.payment_canceled, name = 'payment-cancelled'),
    path('product/<slug>/', views.Product.as_view(), name = "product" ),
    path('checkout/', views.Checkout.as_view(), name = 'checkout'),
    path('order-summary/', views.OrderSummaryView.as_view(), name = 'order-summary'),
    path('add_to_cart/<slug>/', views.add_to_cart, name = 'add_to_cart'),
    path('remove_from_cart/<slug>/', views.remove_from_cart, name = 'remove_from_cart'),
    path('remove_item_from_cart/<slug>/', views.remove_single_item_from_cart, name = 'remove_item_from_cart'),
    path('sell-account/', views.Sell_item.as_view(), name= "sell_account"),
    path('edit-account/<slug>/', views.Sell_item_Update.as_view(), name= "edit_account"),
    path('sale_account/', views.SaleAccountView.as_view(), name='sale_account'),
   
]

dashboard/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "dashboard"

urlpatterns = [
  path('withdraw/', views.WithdrawalView.as_view(), name = "withdraw"),
  path('validate_withdraw/', views.validate_widthrawal, name = "Validate_withdraw"),
  path('transactions/', views.TransactionsView.as_view(), name = "transactions"),
  path('release_payment/', views.Release_Payment.as_view(), name='Release_Payment'),
  path("validate_release/", views.validate_release, name = "validate_release"),
  path("refund/", views.RefundView.as_view(), name = "refund"),
  path("valid_refund/", views.validate_refund, name = "valid_refund"),
  path("notifications", views.order_notification, name ="order_notification"),
  path("email/", views.email_template, name ="email")

]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('', include('Home.urls' , namespace = "Home")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('dashboard/', include('dashboard.urls')),
    path("mobile/", include("MpesaApp.urls")),
    path("unlocks/", include("UnlocksApp.urls")),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from django.forms import ModelForm
from .models import Item
from phonenumber_field.formfields import PhoneNumberField


from bootstrap_modal_forms.forms import BSModalForm

class SaleAccountForm(BSModalForm):
    class Meta:
        model = Item
        fields = "__all__"


PAYMENT_CHOICES = (
('P','Paypal'),
('M','Mpesa')
)
class CheckoutForm(forms.Form):
    street_address = forms.CharField( widget = forms.TextInput(attrs = {
    'placeholder':"Address 1 for street ","class": "form-control"
    }) )
    apartment_address = forms.CharField(required = False, widget = forms.TextInput(attrs = {
    'placeholder':"Address 2 for Apartment or suite","class": "form-control"
    }))
    country = CountryField(blank_label='(select country)').formfield(widget = CountrySelectWidget(attrs = {
    'class': "custom-select d-block w-100"
    }))
    phone_number = PhoneNumberField(widget=forms.TextInput(attrs={'placeholder':('Enter phone number starting with countrycode i,e +2547xxxx '),"class": "form-control" }), 
            label=("Phone number"), required=True)

    zip_code = forms.CharField(widget = forms.TextInput(attrs = {
        "class": "form-control"
    }))
    same_billing_address = forms.BooleanField(required = False)

    save_info =  forms.BooleanField(required = False)

    payment_option =  forms.ChoiceField( widget = forms.RadioSelect, choices=PAYMENT_CHOICES )
    

class Mpesa_checkout(forms.Form):
    
     phone_number = forms.CharField( widget = forms.TextInput(attrs = {
    'placeholder':"2547xxxxxxxxx  "}))
    
class Mpesa_c2b_checkout(forms.Form):

    mpesa_code = forms.CharField( widget = forms.TextInput(attrs = {
    'placeholder':" i.e MNxxxxx "}))

class Sell_item(ModelForm):
    
    class Meta:
        model = Item
        fields = '__all__'
        

dashboard/forms.py
from django import forms
from django.forms import ModelForm
from .models import WithdrawPayouts


class PayoutForm(ModelForm):
    class Meta:
        model = WithdrawPayouts
        exclude = ["user","date","status", "amount_dispensed"]

        

Home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.conf import settings
from . models import Products,Item, OrderItem, Order,BillingAddress
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from .forms import CheckoutForm,Mpesa_checkout, Mpesa_c2b_checkout, SaleAccountForm
from django.urls import reverse,reverse_lazy
from paypal.standard.forms import PayPalPaymentsForm
from django.views.decorators.csrf import csrf_exempt
from rest_framework.generics import CreateAPIView
from rest_framework.permissions import AllowAny
# from .serializers import LNMOnlineSerializer
from djangoProject.mpesa.LipaNaMpesa import lipa_na_mpesa
from rest_framework.response import Response
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import JsonResponse
from notifications.signals import notify
from django.contrib.auth.models import User

import random
import string

sender_batch_id =''.join(
    random.choice(string.ascii_uppercase) for i in range(12)
        
    )

# Create your views here

class SaleAccountView(CreateView):
    template_name = 'sale_account.html'
    form_class = SaleAccountForm
    success_message = 'Success: Book was created.'
    # success_url = reverse_lazy('home')

   
@csrf_exempt
def payment_done(request):
    # order = get_object_or_404(Order, user = request.user, ordered = False)
    # result = callback1_variables()

    context = {
        "result": "hey you"
    }
    
    return render(request, 'payment_done.html' ,context)


@csrf_exempt
def payment_canceled(request):
    return render(request, 'payment_cancelled.html')


def view_paypal(request):
    
    order = Order.objects.get(user =request.user,  ordered = False)
    print(order.id, "this is the cool order number")
    host = request.get_host()
    paypal_email = settings.PAYPAL_RECIEVER_EMAIL
    # orderitem = OrderItem.objects.get(user =request.user,  ordered = False)
    # What you want the button to do.
    print(paypal_email)
    paypal_dict = {

        "business": paypal_email,
        "amount": str(order.get_total()),
        "item_name": 'Order {}'.format(order.id),
        "invoice": sender_batch_id,
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": request.build_absolute_uri(reverse('Home:payment-done')),
        "cancel_return": request.build_absolute_uri(reverse('Home:payment-cancelled')),
        "custom": request.user,  # Custom command to correlate to some function later (optional)
    }


    # Create the instance.
    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {"form": form,
                "order":  order
    }

    
    return render(request, "payment.html", context)

class TakeAccounts(generic.ListView):
    model = Item
    paginate_by = 6
    template_name = "home-page.html"

    def get_queryset(self):
        qs =  super(TakeAccounts, self).get_queryset()

        queryset = qs.filter(category="sw").order_by("-created_at")
        print("index3 called")
       
        return queryset

class BiddingAccounts(generic.ListView):
    model = Item
    paginate_by = 6
    template_name = "home-page.html"

    def get_queryset(self):
        qs =  super(BiddingAccounts, self).get_queryset()

        queryset = qs.filter(category="s").order_by("-created_at")
        print("index3 called")
       
        return queryset

class TranscribingAccounts(generic.ListView):
    model = Item
    paginate_by = 6
    template_name = "home-page.html"

    def get_queryset(self):
        qs =  super(TranscribingAccounts, self).get_queryset()

        queryset = qs.filter(category="OW").order_by("-created_at")
        print("index2 called")
       
        return queryset

class index(generic.ListView):
    model = Item
    paginate_by = 6
    template_name = "home-page.html"

    def get_queryset(self):
        queryset =  super(index, self).get_queryset().order_by("-created_at")
       
        return queryset


class OrderSummaryView(LoginRequiredMixin, generic.View):

    def get(self, *args,**kwargs ):
        try:
            order = Order.objects.get(user = self.request.user,  ordered = False)
            context ={

                'object': order
            }

            return render( self.request, 'order_summary.html' , context )
            messages.error( self.request, "you have an Order" )

        except ObjectDoesNotExist:

            messages.error(self.request, "you do not have an Order")
            return redirect("/")


class Product(generic.DetailView):
    model = Item
    template_name = "product-page.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(Product, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        obj = self.get_object()
        r_item = Item.objects.filter(title = obj.title)[:3]
        nr_item = Item.objects.all()[:3]
        
        context["r_item"] = r_item
        context["nr_item"] = nr_item

        return context


class Checkout(LoginRequiredMixin,generic.View):
    def get(self, *args, **kwargs):
        form = CheckoutForm()
        order = Order.objects.get(user = self.request.user,  ordered = False)

        context = {
            "form": form,
            'order': order
        }
        
        return render(self.request, "checkout-page.html", context )


    def post(self, *args, **kwargs):
 
        form = CheckoutForm(self.request.POST or None)
        print(self.request.POST)
        try:
            order = Order.objects.get(user = self.request.user,  ordered = False)
            
            if form.is_valid():
            
                street_address  = form.cleaned_data.get('street_address')
                print(street_address)

                apartment_address = form.cleaned_data.get('apartment_address')
                print(apartment_address)
                country = form.cleaned_data.get('country')
                print(country)
                zip_code = form.cleaned_data.get('zip')
                same_billing_address = form.cleaned_data.get('same_billing_address')
                save_info = form.cleaned_data.get('save_info')
                payment_option =form.cleaned_data.get('payment_option')
                phone_number = form.cleaned_data.get("phone_number")
                billing_address = BillingAddress(
                    user = self.request.user,
                    street_address = street_address,
                    apartment_address = apartment_address,
                    country = country,
                    phone_number = phone_number,
                    zip_code = zip_code,
                )

                billing_address.save()
                order.billing_address = billing_address

                if payment_option == "P":
                    return redirect("Home:payment"  )
                    
                if payment_option =="M":
                    # messages.info(self.request, "Mpesa payment Mode Not yet Implemented")
                    return redirect("MpesaApp:mpesa_payment")  
                else:
                    messages.warning(self.request, "Invalid payment option selected")
                    print("Invalid payment option selected")
                    return redirect("Home:checkout")
                    
      
                self.request.session['order_id'] = order.id 
            else:
                messages.warning(self.request, "invalid pay")
                print(form.errors)
                print("invalid form")
                return redirect("Home:checkout")

        except ObjectDoesNotExist:

            messages.error(self.request, "you do not have an Order")
            return redirect("/")



@login_required
def add_to_cart(request, slug):

    item = get_object_or_404(Item, slug= slug)
    order_item,created = OrderItem.objects.get_or_create(item = item ,user = request.user, ordered = False)
    order_qs = Order.objects.filter(user = request.user, ordered = False)
    seller_id = item.created_by.id
    user = User.objects.get(id=seller_id)

    print(item.created_by,"this is the seller")
    print(seller_id,"this is the seller's id")
    if order_qs.exists():
        order = order_qs[0]

        if order.items.filter(item__pk = item.pk).exists():
            
            order_item.quantity += 1

            order_item.save()

            messages.info(request, "This item quantity was updated to your cart ")

            return redirect("Home:order-summary")

        else:
            messages.info(request, "This item was added to your cart ")
            print("this is from  orderitem")
            order.items.add(order_item)
            order.seller = user
            order.save()

            return redirect("Home:order-summary")
    else:
      
        ordered_date = timezone.now()
        order = Order.objects.create(user = request.user, ordered_date = ordered_date, seller = user)
        order.items.add(order_item)
        print("this is from  order")

        messages.info(request, "This item was added to your cart ")
        
    return redirect("Home:order-summary")

@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug= slug)
    order_qs = Order.objects.filter(user = request.user, ordered = False)

    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order

        if order.items.filter( item__pk = item.pk ).exists():
            order_item = OrderItem.objects.filter( item = item , user = request.user, ordered = False )[0]

            order.items.remove(order_item)

Home/templates/dashboard/email.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    
    <!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Google Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.0/css/mdb.min.css" rel="stylesheet">
</head>
<body>

    <main class = 'container'>
            <!-- Card Narrower -->
        <div class="card card-cascade narrower">

            <!-- Card image -->
            <div class="view view-cascade overlay">
            <img class="card-img-top" src="{% static 'logo.png' %}"
                alt="Freelancing Account">
            <a>
                <div class="mask rgba-white-slight"></div>
            </a>
            </div>
        
            <!-- Card content -->
            <div class="card-body card-body-cascade">
        
            <!-- Label -->
            <h5 class="pink-text pb-2 pt-1"><i class="fas fa-bell"></i></i> Notification</h5>
            <!-- Title -->
            <h4 class="font-weight-bold card-title">{{order.title}}</h4>
            <!-- Text -->
            <p class="card-text">{{order.text}}</p>
            <!-- Button -->
            <a href="https://freelancingaccounts.com" class="btn btn-unique"> Check it out </a>

            </div>
        
        </div>
        <!-- Card Narrower -->
    </main>
</body>
</html>

Home/templates/dashboard/refund.html
<!DOCTYPE html>
{% extends 'base.html'%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Refund</title>
</head>
<body>
{% block content%}

<Main class="container">

    <h1 class="text-center "> <i> Request Refund </i></h1>

  <ul class="nav nav-tabs md-tabs " id="myTabMD" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="home-tab-md" data-toggle="tab" href="#home-md" role="tab" aria-controls="home-md"
        aria-selected="true">Request Refund</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="profile-tab-md" data-toggle="tab" href="#profile-md" role="tab" aria-controls="profile-md"
        aria-selected="false">  Refund History  </a>
    </li>
    
  </ul>
  <div class="tab-content " id="myTabContentMD">
    <div class="tab-pane fade show active" id="home-md" role="tabpanel" aria-labelledby="home-tab-md">
      <div class="card">
        <h3 class="card-header"> Select which order you want to refund</h3>
        <div class="table-responsive  text-nowrap">
            
 
            <!--Table-->
            <table class="table table-hover ">
    
              <!--Table head-->
              <thead>
                <tr>
                  <th>#</th>
                  <th>Orderid</th>
                  <th>Date</th>
                  <th>Item</th>
                  <th>amount</th>
                  <th>Seller</th>
                  <th>Refund</th>
                  
                </tr>
              </thead>
              <!--Table head-->
    
              <!--Table body-->
              <tbody>

               {% for object in object_list%} 
                <tr style="height:min-content">
                  <th scope="row">{{forloop.counter}}</th>
                  <td>{{ object.id }}</td>
                  <td>{{ object.ordered_date }}</td>
                  <td>

                    {% for obj in object.items.all %}

                    <p> {{ obj.item.title }} </p>

                  {% endfor %}
                  </td>
                  <td>{{ object.amount }}</td>
                  <td>{{ object.seller }}</td>
                  <td>
                    <button id="btn"  class="btn btn-primary" onclick="refund(this);" data-toggle="modal" data-target="#modalRegisterForm">Refund Money</button>
                    
                    <button id="loadbtn" style="display: none; height:min-content" class="btn btn-primary" type="button" disabled>
                      <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                      Loading...
                    </button>
                  
                  </td>
                  
                </tr>

                {% empty %}
                <tr>
                  <th scope="row"></th>
                  <td colspan="5"> You have no previous orders to refund you Money </td>
                  
                </tr>
                {% endfor %}
 
              </tbody>
              <!--Table body-->
    
    
            </table>
            <!--Table-->
          </div>

    </div>
    </div>

    <div class="tab-pane fade" id="profile-md" role="tabpanel" aria-labelledby="profile-tab-md">
      <div class="card" style="overflow-y:scroll; height:400px;"> 
        <h4 class="card-header"> Refund History</h4>
        <div class="table-responsive  text-nowrap">
            
    
            <!--Table-->
            <table class="table table-hover ">
    
              <!--Table head-->
              <thead>
                <tr>
                  <th>#</th>
                  <th>Orderid</th>
                  <th>Date</th>
                  <th>amount</th>
                  <th> Status</th>
                  
                  
                  
                </tr>
              </thead>
              <!--Table head-->
    
              <!--Table body-->
              <tbody>
    
               {% for object in refund %} 
                <tr>
                  <th scope="row">{{forloop.counter}}</th>
                  <td>{{ object.orderid }}</td>
                  <td>{{object.date}}</td>
                  <td>{{ object.amount }}</td>
                  <td>
    
                    {% if object.status %}
    
                    <span class="badge success badge-pill"> Paid </span>
    
                    {% else %}
    
                    <span class="badge purple badge-pill" style="font-size: medium;"> pending... </span>
    
                    {% endif %}
    
    
    
                  </td>
                              
                </tr>
    
                {% empty %}
                <tr>
                  <th scope="row"> </th>
                  <td colspan="4"> You have no previous orders to refund you Money </td>
                  
                </tr>
                {% endfor %}
    
              </tbody>
              <!--Table body-->
    
    
            </table>
            <!--Table-->
          </div>
    
    </div>
    </div>
    
  </div>
</Main>



<hr class="mt-5">

   

    <!-- Central Modal Medium Success -->
<div class="modal fade" id="centralModalSuccess" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog modal-notify modal-success" role="document">
  <!--Content-->
  <div class="modal-content">
    <!--Header-->
    <div class="modal-header">
      <p class="heading lead"> Request Success </p>

      <button type="button" class="close" data-dismiss="modal" onclick="location.reload(true);" aria-label="Close">
        <span aria-hidden="true" class="white-text">&times;</span>
      </button>
    </div>

    <!--Body-->
    <div class="modal-body">
      <div class="text-center">
        <i class="fas fa-check fa-4x mb-3 animated rotateIn delay-1s"></i>
        
        Request is sucessful and pending Release. We will look forward to working with you again.
       Your money will be refunded to you in less than 24 hours.
        
      </div>
    </div>

    <!--Footer-->
    <div class="modal-footer justify-content-center">
     
      <a type="button" class="btn btn-outline-success waves-effect" onclick="location.reload(true);" data-dismiss="modal">Dismiss</a>
    </div>
  </div>
  <!--/.Content-->
</div>
</div>
<!-- Central Modal Medium Success-->

      
 <!-- reason popup  -->
 <div class="modal fade" id="modalRegisterForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
 aria-hidden="true">
 <div class="modal-dialog" role="document">
   <div class="modal-content">
     <div class="modal-header text-center">
       <h4 class="modal-title w-100 font-weight-bold">Request Reason</h4>
       <button type="button" class="close" data-dismiss="modal" onclick="loadstop();" aria-label="Close">
         <span aria-hidden="true">&times;</span>
       </button>
     </div>
     <div class="modal-body mx-3">
       <form method="GET" class="postreason">
       
       <label>Select Reason</label>
       <select id="select" class="browser-default custom-select mb-4" onchange="yesnoCheck(this);" required>
           <option value="" selected> Choose option </option>
           <option value="The seller did not give logins" >The seller did not give logins </option>
           <option value="The Account is not Genuine"> The Account is not Genuine </option>
           <option value="The Seller refused to give certificate ">The Seller refused to give certificate  </option>
           <option value="Other"> Other</option>
       </select>

   
       <!-- Message -->
       <div style="display: none;" id="other" class="form-group">
           <textarea class="form-control rounded-0" id="other-reason" rows="3" placeholder="Kindly Specify"></textarea>
       </div>

       
       <div class="custom-control custom-radio">
        <input type="radio" class="custom-control-input" id="id_mpesa" name="mode" value="mpesa">
        <label class="custom-control-label" for="id_mpesa">Mpesa</label>
      </div>
      
      
      <div class="custom-control custom-radio">
        <input type="radio" class="custom-control-input" id="id_paypal" name="mode"  value="paypal">
        <label class="custom-control-label" for="id_paypal">Paypal</label>
      </div>

     </div>
     <div class="modal-footer d-flex justify-content-center">
       <button type="submit" class="btn btn-primary"> Submit </button>
     </div>

    </form> 
   </div>
 </div>
</div>
{% endblock %}

{% block scripts %}
 <!-- reason popup  -->
<script>
  function yesnoCheck(that) {
    if (that.value == "Other") {
      $("#other").show();
    }
  
  }
  function loadstop() {
    $("#btn").show()
    $("#loadbtn").hide()
  }

 $(".postreason").on("submit", function(e){
   e.preventDefault();
   $("#modalRegisterForm").modal("hide")
   $(".modal-backdrop").remove()
   

   var select = $("#select").val();
   var other = $("#other-reason").val();
   var mode =  $("[name='mode']:checked").val()
   var data = Window.data;
  data["select"] = select
  data["other"] = other
  data["mode"]= mode
  console.log(data)
  $.ajax({
      url:"{% url 'dashboard:valid_refund' %}",
      type:"GET",
      async:true,
      dataType:"json",
      data : data,
      success: function(data) {

        if (data.message =="successful"){

        $("#centralModalSuccess").modal("show");
        $("#btn").show()
        $("#loadbtn").hide()

        }
        else {
          alert(data.message);
        }

 
      },



    })

 })


  function refund(ctl) {
    var row = $(ctl).parents("tr")
    $("#btn").hide();
    $("#loadbtn").show();


    var cols = row.children("td");

    
    item1 =$(cols[2]).text();

    item =item1.replace(/(\r?\n|\r)/gm, '').trim();

    console.log(item1, item)
    Window.data ={
      "orderid" : $(cols[0]).text(),
      "date" : $(cols[1]).text(),
      "item": item,
      "amount": $(cols[3]).text(),
      "seller":$(cols[4]).text(),

    }
    
  
    
    
  console.log(Window.data)
  }
</script>
{% endblock %}

</body>
</html>